### PR TITLE
Fix issue 1090 hook code unicity

### LINKED ISSUE #1090: Hook code unicity is not checked when creating a new hook
When a new hook is created, Thelia doesn't check code unicity. 

For example, it's possible to create several 'home.top' hooks.

We can check unicity in the `HookCreationForm`, but we have to define a class validator, as we need both hook code and hook type fields value. Is it possible in a Thelia form ?

### PR DESCRIPTION
**Pull request by TomPradat**
Function to check code unicity during HookCreationForm added with a Callback
Resolve #1090

### CODE REVIEW

File: core/lib/Thelia/Form/HookCreationForm.php [hunk 1]
```diff
@@ -81,6 +87,19 @@ protected function buildForm()
         ;
     }
 
+    public function checkCodeUnicity($code, ExecutionContextInterface $context){
+        $count = HookQuery::create()->filterByCode($code)->count();
```
Comment (bibich) [inline core/lib/Thelia/Form/HookCreationForm.php]: You have to check the type of the hook too, as you can have two hooks with the same code, one used in the front office, the other in the back office.
