### PR TITLE
Fixes

### LINKED ISSUE #2014: In 2.3 alpha2, it is not possible to create a new tax
Even if is not used, the "feature" value seems mandatory : 

img-2016-02-25_19-41-23

### PR DESCRIPTION
**Pull request by bibich**
- Prevent multiple form submissions in back office modal forms
- Cleanup hooks and discover function
- Added possibility to translate tax type requirement
- Fixes #2014 : new taxes can be created

### CODE REVIEW

File: setup/insert.sql [hunk 1]
```diff
@@ -321,7 +321,19 @@ INSERT INTO `hook` (`id`, `code`, `type`, `by_module`, `block`, `native`, `activ
 (220, 'account-order.javascript-initialization', 1, 0, 0, 1, 1, 1, NOW(), NOW()),
 (221, 'account.additional', 1, 0, 1, 1, 1, 1, NOW(), NOW()),
 (222, 'account-order.product', 1, 0, 0, 1, 1, 1, NOW(), NOW()),
-(223, 'mini-cart', 1, 0, 0, 1, 1, 1, NOW(), NOW())
+(223, 'mini-cart', 1, 0, 0, 1, 1, 1, NOW(), NOW()),
+(224, 'sale.top', 1, 0, 0, 1, 1, 1, NOW(), NOW()),
```
Comment (gillesbourgeat) [inline setup/insert.sql]: This is a backOffice hook ? The type must be 2 and the id must be in range 1xxx.

Comment (bibich) [inline setup/insert.sql]: No no, it's front office hooks.

**Comment by gillesbourgeat** [comment]
Thanks !
