### PR TITLE
fix product price exports

### LINKED ISSUE #1078: Export Prix produits hors-taxes + TTC
Cela n'exporte qu'une partie des produits
pour le Hors-taxes  -> les produits d'une seule categorie
pour TTC  -> 1 seul produit

version 2.0.4 et 2.1.1

### LINKED ISSUE #1610: Exporting products including taxes gives excluding taxes prices and not all products
When using the export tool for products including taxes :
- prices are without taxes
- the "ID" column is filled with product IDs
- the file exports the number of products instead of the number of PSEs / product prices (e.g. : if there are 420 products & 1770 PSEs, only 420 prices are exported)

This might be linked with issue #1078

### PR DESCRIPTION
**Pull request by ThomasArnaud**
Resolve #1078
Resolve #1610

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Hello,
You break the unit tests !

File: core/lib/Thelia/ImportExport/Export/Type/ProductPricesExport.php [hunk 1]
```diff
@@ -128,12 +130,12 @@ public function getOrder()
             "id",
             "product_id",
             "title",
-            "attributes",
```
Comment (gillesbourgeat) [inline core/lib/Thelia/ImportExport/Export/Type/ProductPricesExport.php]: Why did you move the output value "attribute" ?

**Comment by gillesbourgeat** [comment]
Your PR does not solve the problem. If a product have not a combination of attributes, it is not in the export.
I tested with the "Product prices excluding taxes" export

**Comment by gillesbourgeat** [comment]
Thanks !
